### ISSUE TITLE
Task: Better Project Name

### ISSUE THREAD

**Issue by christine-morgado** [stretchyDog/CircuitsMadeEasy#1]
# Better Project Name

## Description

Our project needs a better name... help us come up with one!

## Subtasks

- [ ] [Everyone suggests 2-3 names]
- [ ] [Everyone votes on a name]
- [ ] [Name is changed in all places where applicable]

## Acceptance Criteria

- [ ] Everyone agrees on name: <name here>
- [ ] Name is changed in all places where applicable
